name: Flutter Integration Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build apk with flutter
        run: flutter build apk --debug

      - name: Build Android test APK
        run: |
          cd android
          ./gradlew clean
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget=test_driver/integration_test_driver.dart

      - name: List all files for debugging
        run: |
          echo "Listing all files:"
          find .

      - name: Verify APK paths
        run: |
            echo "Listing debug APK:"
            ls -l ./build/app/outputs/apk/debug/app-debug.apk
            echo "Listing test APK:"
            ls -l ./build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk

      - name: Run tests in Firebase Test Lab
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 --decode > $HOME/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json
          gcloud --quiet config set project instastory-428913
          
          gcloud firebase test android run \
              --type instrumentation \
              --app ./build/app/outputs/apk/debug/app-debug.apk \
              --test ./build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --timeout 10m
        env:
            GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-service-key.json
