name: Flutter Integration Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration_test:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: cirrusci/flutter:latest
        options: --privileged
        ports:
          - 5900:5900

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6' # Set the Flutter version to your project's version

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Android SDK
        run: sudo apt-get install -y openjdk-8-jdk wget tar unzip
      - name: Download Android command line tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O commandlinetools-linux.zip
          unzip commandlinetools-linux.zip -d android-sdk
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3" "emulator" "system-images;android-30;google_apis;x86_64"
      - name: Create and start emulator
        run: |
          echo "no" | android-sdk/cmdline-tools/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"
          android-sdk/emulator/emulator -avd test -no-audio -no-window &
          android-sdk/platform-tools/adb wait-for-device
      - name: Wait for emulator to start
        run: sleep 60

      - name: Integration tests
        run: |
          flutter devices
          flutter drive \
            --driver=test_driver/integration_test_driver.dart \
            --target=integration_test/app_test.dart -d emulator-5554
