name: Flutter Integration Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.6' # Set the Flutter version to your project's version

    - name: Install dependencies
      run: flutter pub get

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Download and set up Android SDK
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y openjdk-11-jdk wget unzip
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d .
        mv cmdline-tools latest
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        source $GITHUB_ENV

    - name: Install Android SDK components
      run: |
        sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86_64" "emulator"
        yes | sdkmanager --licenses

    - name: Verify installed components
      run: |
        echo "Installed system images:"
        ls $ANDROID_SDK_ROOT/system-images/android-30/
        echo "Installed platforms:"
        ls $ANDROID_SDK_ROOT/platforms/
        echo "Installed build-tools:"
        ls $ANDROID_SDK_ROOT/build-tools/
        echo "Installed emulator:"
        ls $ANDROID_SDK_ROOT/emulator/

    - name: List installed system images
      run: sdkmanager --list

    - name: List available AVD targets
      run: avdmanager list target

    - name: Create and start emulator
      run: |
        echo "Creating AVD..."
        avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
        echo "Starting emulator..."
        $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-snapshot -no-window -no-audio &

    - name: Wait for emulator to boot
      run: |
        adb wait-for-device
        adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

    - name: Run integration tests
      run: |
        flutter devices
        flutter drive \
          --driver=test_driver/integration_test_driver.dart \
          --target=integration_test/story_detail_screen_test.dart -d emulator-5554
