name: Flutter Integration Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build apk with flutter
        run: flutter build apk --debug

      - name: Build Android test APK
        run: |
          cd android
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget=test_driver/integration_test_driver.dart

      - name: Set up Firebase CLI
        run: curl -sL https://firebase.tools | bash
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 --decode > $HOME/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json
          gcloud --quiet config set project instastory-428913


      - name: Run tests in Firebase Test Lab
        run: |
          gcloud firebase test android run \
            --type instrumentation \
            --app build/app/outputs/flutter-apk/app-release.apk \
            --test build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --device model=Pixel2,version=29,locale=en,orientation=portrait
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-service-key.json
