name: Flutter Integration Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.6' # Set the Flutter version to your project's version

    - name: Install dependencies
      run: flutter pub get

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Cache Android SDK
      uses: actions/cache@v2
      with:
        path: ${{ runner.temp }}/android-sdk
        key: ${{ runner.os }}-android-sdk

    - name: Download and set up Android SDK
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y openjdk-11-jdk wget unzip
        mkdir -p ${{ runner.temp }}/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d ${{ runner.temp }}/android-sdk/cmdline-tools
        mv ${{ runner.temp }}/android-sdk/cmdline-tools/cmdline-tools ${{ runner.temp }}/android-sdk/cmdline-tools/latest
        echo "ANDROID_SDK_ROOT=${{ runner.temp }}/android-sdk" >> $GITHUB_ENV
        echo "PATH=${{ runner.temp }}/android-sdk/cmdline-tools/latest/bin:${{ runner.temp }}/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Install Android SDK components
      env:
        ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      run: |
        ${{ runner.temp }}/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86_64" "emulator"
        yes | ${{ runner.temp }}/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Create and start emulator
      run: |
        ${{ runner.temp }}/android-sdk/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
        nohup ${{ runner.temp }}/android-sdk/emulator/emulator -avd test -no-snapshot -no-window -no-audio &

    - name: Wait for emulator to boot
      run: |
        adb wait-for-device
        adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

    - name: Run integration tests
      run: |
        flutter devices
        flutter drive \
          --driver=test_driver/integration_test_driver.dart \
          --target=integration_test/story_detail_screen_test.dart -d emulator-5554
